[tool.poetry]
name = "my_python_project"
version = "0.1.0"
description = ""
authors = ["CoReason, Inc. <gowtham.rao@coreason.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
ruff = "^0.14.2"
mypy = "^1.18.2"
pre-commit = "^4.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
