{% raw %}
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.14'

      - name: Build Docs
        run: uv run zensical build
        shell: bash

      - name: Build package
        run: uv build
        shell: bash

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./dist
          format: spdx-json
          output-file: dist/sbom.spdx.json

      - name: Sign artifacts with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            dist/*.tar.gz
            dist/*.whl

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
{% endraw %}
